/**
 * Autogenerated by Thrift Compiler (0.13.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef helmet_CONSTANTS_H
#define helmet_CONSTANTS_H

#include "helmet_types.h"



class helmetConstants {
 public:
  helmetConstants();

};

extern const helmetConstants g_helmet_constants;



#endif
