// This autogenerated skeleton file illustrates how to build a server.
// You should copy it to another filename to avoid overwriting it.

#include "Helmet.h"
#include <thrift/protocol/TBinaryProtocol.h>
#include <thrift/server/TSimpleServer.h>
#include <thrift/transport/TServerSocket.h>
#include <thrift/transport/TBufferTransports.h>

using namespace ::apache::thrift;
using namespace ::apache::thrift::protocol;
using namespace ::apache::thrift::transport;
using namespace ::apache::thrift::server;

class HelmetHandler : virtual public HelmetIf {
 public:
  HelmetHandler() {
    // Your initialization goes here
  }

  void checkHelmet(HelmetCheckResult& _return, const std::string& image) {
    // Your implementation goes here
    printf("checkHelmet\n");
  }

  void pingHelmet() {
    // Your implementation goes here
    printf("pingHelmet\n");
  }

};

int main(int argc, char **argv) {
  int port = 9090;
  ::std::shared_ptr<HelmetHandler> handler(new HelmetHandler());
  ::std::shared_ptr<TProcessor> processor(new HelmetProcessor(handler));
  ::std::shared_ptr<TServerTransport> serverTransport(new TServerSocket(port));
  ::std::shared_ptr<TTransportFactory> transportFactory(new TBufferedTransportFactory());
  ::std::shared_ptr<TProtocolFactory> protocolFactory(new TBinaryProtocolFactory());

  TSimpleServer server(processor, serverTransport, transportFactory, protocolFactory);
  server.serve();
  return 0;
}

