/**
 * Autogenerated by Thrift Compiler (0.13.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "helmet_constants.h"



const helmetConstants g_helmet_constants;

helmetConstants::helmetConstants() {
}



