/**
 * Autogenerated by Thrift Compiler (0.13.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef person_CONSTANTS_H
#define person_CONSTANTS_H

#include "person_types.h"



class personConstants {
 public:
  personConstants();

};

extern const personConstants g_person_constants;



#endif
